name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files

    - name: run fastapi web test
      run: nohup uvicorn main:app --host 127.0.0.1 --port 8000 &

    - name: Test FastAPI health endpoint
      run: |
        sleep 5  # 等待服务启动
        curl -f http://127.0.0.1:8000/healthz
